/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sudoku;

import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JTextField;
import javax.swing.Timer;

/**
 *
 * @author Asus
 */
public class SudokuGUI extends javax.swing.JFrame {

    /**
     * Creates new form SudokuGUI
     */
    public SudokuGUI() {
        initComponents();
        bannerAnimation();
    }

    
    void bannerAnimation(){
        String bannerText = jLabel2.getText();
        int bannerLength = bannerText.length();
        
        Timer timer = new Timer(100, new ActionListener(){
        
         int pos = 0;
         @Override 
         public void actionPerformed(ActionEvent e){
         pos = (pos+1) % bannerLength;
         jLabel2.setText(bannerText.substring(pos) + bannerText.substring(0, pos));
         
         }
        
        }
        );
        
        timer.start();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        StartGame = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        difficultyComboBox = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 360, 330));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Enter Grid Size:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, 40));

        StartGame.setText("Start Game");
        StartGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartGameActionPerformed(evt);
            }
        });
        getContentPane().add(StartGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 120, 40));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 204, 255));
        jLabel2.setText("This Game is made solely for entertainmaint purpose only by Shubhangi Pawar. All rights reserved. Hope you have fun!!");
        jPanel3.add(jLabel2);

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 870, 40));

        difficultyComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Level 1", "Level 2", "Level 3" }));
        difficultyComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                difficultyComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(difficultyComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 150, 40));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 90, 40));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, -1, -1));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, 260, 40));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 170, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StartGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartGameActionPerformed
        // TODO add your handling code here:
         jTextField3.removeAll();
        
        String InputGridSize = jTextField1.getText();
         gridSize =  Integer.parseInt(InputGridSize);
       // int difficultyLevel = difficultyComboBox.getSelectedIndex() + 1;
        SudokuHelper game = new SudokuHelper(gridSize,Integer.parseInt(difficultyComboBox.getItemAt(difficultyComboBox.getSelectedIndex()).charAt(6)+""));
           int[][] arr = game.board;
        jPanel1.setLayout(new GridLayout(gridSize, gridSize));
        jPanel1.removeAll();
        
        textField = new JTextField[gridSize][gridSize];
         
        
        
        for(int i=0; i<gridSize; i++){
            for(int j=0; j<gridSize; j++){
                textField[i][j] = new JTextField(2);
                jPanel1.add(textField[i][j]);
            }
        }
        for(int i=0;i<gridSize;i++){
            for(int j=0;j<gridSize;j++){
                if(arr[i][j]!=0){
                textField[i][j].setText(arr[i][j]+"");
                textField[i][j].setEditable(false);
            }    }
        }
        jPanel1.repaint();
         jPanel1.validate(); 
       
//        JoptionPane.showMessageDialog(null, "Please enter a valid Grid");
        
    }//GEN-LAST:event_StartGameActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void difficultyComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_difficultyComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_difficultyComboBoxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int count = 1;
          for(int i=0; i<gridSize;i++){
              for(int j=0;j<gridSize;j++){
                  if(isUsedBefore(i,j,textField[i][j])){
                    jTextField3.setText("Incorrect answer. Try again!");
                    return;
                  }else{
                      count++;
                  }
              }
          }
          if(count==gridSize){
          jTextField3.setText("Congratulations!"); 
          }
    }//GEN-LAST:event_jButton1ActionPerformed

    private boolean isUsedBefore(int row,int col,JTextField field){
         for(int i=0;i<gridSize;i++){
            if(textField[row][i].getText().trim().equals(field.getText().trim())){
                return true;
            }
        }
        
        for(int i=0;i<gridSize;i++){
            if(textField[i][col].getText().trim().equals(field.getText().trim())){
                return true;
            }
        }
        
       
      return false;  
    }
    static JTextField[][] textField;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SudokuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SudokuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SudokuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SudokuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SudokuGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton StartGame;
    private javax.swing.JComboBox<String> difficultyComboBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
      private int gridSize;
    private static class JoptionPane {

        private static void showMessageDialog(Object object, String please_enter_a_valid_Grid) {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        public JoptionPane() {
        }
    }

    
}
